/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sprite;

import Interfaz.Interfaz;
import ListasYPilas.ListaEnlazada;
import Pixel.Pixel;
import java.awt.GridLayout;

/**
 *
 * @author samuelson
 */
public class Sprite extends javax.swing.JPanel {
    /**
     * Creates new form Sprite
     */
    Interfaz interfaz;
    public Sprite() {
        initComponents();
    }
    public void crearSprite(int filas, int columnas){
        setLayout(new GridLayout(filas,columnas));
        int total = (filas*columnas);
        ListaEnlazada <Pixel> pixeles = new ListaEnlazada();
        
        for (int i = 0; i < total; i++) {
            Pixel pixel = new Pixel();
            add(pixel);
            pixeles.add(pixel);
        }
        interfaz.setPixeles(pixeles);
    }

    public Interfaz getInterfaz() {
        return interfaz;
    }

    public void setInterfaz(Interfaz interfaz) {
        this.interfaz = interfaz;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
